# fly.toml file generated for sats4likesbot on 2022-09-01T10:31:19+02:00

app = "sats4likesbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.7"
    NODE_VERSION = "14.17.3"
    RUBY_VERSION = "2.7.6"

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
